modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license="MIT"

[[mods]]
modId="carpetvariants"
version = "${version}"
displayName="CarpetVariants"
authors="ludwici"
description='''A mod that gives you the ability to place carpets on walls and ceilings.'''
#logoFile = ""

[[dependencies.carpetvariants]]
modId="forge"
mandatory=true
versionRange = "[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.carpetvariants]]
modId="minecraft"
mandatory=true
versionRange = "[1.19.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.carpetvariants]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"