modLoader = "javafml"
loaderVersion="${neo_loader_version_range}"
#issueTrackerURL = ""
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version = "${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "logo.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange="${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="carpetscore"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
